### ISSUE TITLE
[Style] body태그 우측 margin 0으로 보임

### ISSUE THREAD

**Issue by 0805004949** [k8s12-CacaoEnt/profile-box-front#1]
![image](https://github.com/k8s12-CacaoEnt/profile-box-front/assets/88617600/995c6c11-4ff5-48d6-9ae1-056eb9efc658)
```css
body {
  width: 100%;
  }
```

인데 우측 body에 margin:0처럼 보임ㅇ
